// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Coach struct {
	ID        string `json:"ID"`
	ImageURL  string `json:"ImageUrl"`
	Name      string `json:"Name"`
	Specialty string `json:"Specialty"`
}

type Goal struct {
	ID          string `json:"ID"`
	Name        string `json:"Name"`
	Description string `json:"Description"`
	StartDate   string `json:"StartDate"`
	EndDate     string `json:"EndDate"`
}

type Mutation struct {
}

type NutritionLog struct {
	ID          string `json:"ID"`
	UserID      string `json:"UserID"`
	Description string `json:"Description"`
	Calories    int    `json:"Calories"`
	Date        string `json:"Date"`
}

type Post struct {
	ID        string `json:"ID"`
	UserEmail string `json:"UserEmail"`
	Title     string `json:"Title"`
	Content   string `json:"Content"`
	CreatedAt string `json:"CreatedAt"`
}

type Query struct {
}

type User struct {
	ID    string `json:"ID"`
	Email string `json:"Email"`
}

type UserProfile struct {
	Age    *int     `json:"Age,omitempty"`
	Height *float64 `json:"Height,omitempty"`
	Weight *float64 `json:"Weight,omitempty"`
}

type WorkoutLog struct {
	ID       string  `json:"ID"`
	UserID   string  `json:"UserID"`
	Exercise string  `json:"Exercise"`
	Sets     int     `json:"Sets"`
	Reps     int     `json:"Reps"`
	Weight   float64 `json:"Weight"`
	Date     string  `json:"Date"`
}
