// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Coach struct {
	ID        string `json:"ID"`
	Name      string `json:"Name"`
	Specialty string `json:"Specialty"`
}

type FitnessGoal struct {
	ID          string  `json:"ID"`
	UserID      string  `json:"UserID"`
	Description string  `json:"Description"`
	TargetDate  *string `json:"TargetDate,omitempty"`
	Achieved    *bool   `json:"Achieved,omitempty"`
}

type Mutation struct {
}

type NutritionLog struct {
	ID          string `json:"ID"`
	UserID      string `json:"UserID"`
	Description string `json:"Description"`
	Calories    int    `json:"Calories"`
	Date        string `json:"Date"`
}

type Query struct {
}

type User struct {
	ID            string          `json:"ID"`
	Name          string          `json:"Name"`
	Email         string          `json:"Email"`
	Profile       *UserProfile    `json:"Profile,omitempty"`
	Goals         []*FitnessGoal  `json:"Goals,omitempty"`
	Workouts      []*WorkoutLog   `json:"Workouts,omitempty"`
	NutritionLogs []*NutritionLog `json:"NutritionLogs,omitempty"`
}

type UserProfile struct {
	Age    *int     `json:"Age,omitempty"`
	Height *float64 `json:"Height,omitempty"`
	Weight *float64 `json:"Weight,omitempty"`
}

type WorkoutLog struct {
	ID       string  `json:"ID"`
	UserID   string  `json:"UserID"`
	Exercise string  `json:"Exercise"`
	Sets     int     `json:"Sets"`
	Reps     int     `json:"Reps"`
	Weight   float64 `json:"Weight"`
	Date     string  `json:"Date"`
}
